### ISSUE TITLE
Composite actions are not supported

### ISSUE THREAD

**Issue by igdianov** [Wandalen/wretry.action#115]
The Retry action is quitting silently with success exit code 0 when a composite action is used with it. It looks like only `node` actions are supported at the moment, but it is not obvious to users due to this check: https://github.com/Wandalen/wretry.action/blob/js_action/src/Retry.js#L52-L54.

**Comment by dmvict** [comment]
Hello @igdianov 

The action supports only  nodejs actions. Here is [description of features](https://github.com/Wandalen/wretry.action#features).

I did no added the tests for unsupported action types. The check of the type you can find in [line 60](https://github.com/Wandalen/wretry.action/blob/js_action/src/Retry.js#L60). You've given the condition for `pre` and `post` steps. 

We are adding basic support of Docker actions in https://github.com/Wandalen/wretry.action/pull/60. But we do not plan to write a runner for composite actions because composite action is a workflow inside action. The action can retry single command or nodejs action but not workflow.

**Comment by dmvict** [comment]
Hello @igdianov 

[Here](https://github.com/Wandalen/wretry.action/pull/117/files#diff-bd52654af6a75bc141718a0f9b569465c7e9b4b6c0b8c7771c06694b55750a6fR118) I covered the case with unsupported action types. The action should throw error for `composite` action. 

If you need to retry composite action, extract its steps and retry them, please.
