### ISSUE TITLE
[request] loop/matrix action

### ISSUE THREAD

**Issue by ReenigneArcher** [Wandalen/wretry.action#159]
Given that you have successfully created a retry action, it would be a nice addition if you could support a similar type of action (or extend this action to support it).

I am looking for a loop action. In my case specifically I'd like a `matrix` equivalent for steps instead of jobs. I have also seen other's searching for other loops, such as `for each`.

I understand if you don't want to take this on, so no hard feelings if you decide to close this. In any event thank you for the `wretry.action` as it has helped me solve some issues in the past!

**Comment by dmvict** [comment]
Hello @ReenigneArcher 

It's idea for the other action because the current action retries failed steps. You required the action that should run an action in a cycle with different inputs. I guess somebody can use the ideas from the current action to implement the required features. 
Sorry, I cannot implement and support an additional action.
